name: Code Review

on:
  pull_request:
    types: [opened, reopened, synchronize, review_requested]

jobs:
  ai-review:
    name: AI Code Review
    uses: Leuchtfeuer/mautic-ci-runner/.github/workflows/ai_review.yaml@212d55114eb09d887b16bf414a5fec5d3919c212
    secrets:
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
